name: Release Native Image via Homebrew
on:
  release:
    types: [published]
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest
            uploaded_filename: zio-app-x86_64-apple-darwin.gz
            local_path: cli/target/native-image/zio-app.gz
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: git fetch --tags || true
      - run: sh release.sh
        shell: bash
      - run: echo $(pwd)
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        id: upload-release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
      - name: bump-homebrew-formula
        if: github.event_name == 'release'
        uses: mislav/bump-homebrew-formula-action@v1.12
        with:
          formula-name: zio-app
          base-branch: master
          download-url: ${{ steps.upload-release.outputs.browser_download_url }}
          homebrew-tap: kitlangton/homebrew-zio-app
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
