name: Native Image
on:
  push:
    branches:
      - master
      - main
  pull_request:
  release:
    types: [published]
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest
            uploaded_filename: zio-app-x86_64-apple-darwin
            local_path: target/native-image/zio-app.gz
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: git fetch --tags || true
      - run: sh release.sh
        shell: bash
      - run: echo $(pwd)
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
